version: '3.7'
services:
  db:
    image: mongo:3.6
    command: mongod --smallfiles --bind_ip_all
    ports:
      - "127.0.0.1:27017:27017"
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./script/start
    ports:
      - "3000:3000"
    links:
      - db
    stdin_open: true
    tty: true  
    volumes:
      - .:/workspace
      - bundler:/usr/local/bundle        
volumes:
  bundler: {}
