FROM ruby:2.6
ENV BUNDLE_PATH /usr/local/bundle

RUN mkdir /workspace
WORKDIR /workspace

ADD Gemfile /workspace/Gemfile
ADD Gemfile.lock /workspace/Gemfile.lock
ADD script /workspace/script

RUN bundle install --jobs 4

ADD . /workspace