version: '3.7'
services:
  db:
    image: postgres
      restart: always
    environment:
      POSTGRES_PASSWORD: example

    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./script/start
    volumes:
      - .:/workspace
      - bundler:/bundler
    ports:
      - "3000:3000"
    links:
      - db
    stdin_open: true
    tty: true
volumes:
  bundler: {}
