version: '3.7'
services:
  db:
    image: neo4j:3.5
    ports:
      - "17474:7474"
  api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    command: ./script/start
    volumes:
      - .:/workspace
      - bundler:/bundler
    ports:
      - "3000:3000"
    links:
      - db
    stdin_open: true
    tty: true
volumes:
  bundler: {}
